# yaml-language-server: $schema=./schema.default.json
# SPDX-FileCopyrightText: Contributors to PyPSA-Eur <https://github.com/pypsa/pypsa-eur>
#
# SPDX-License-Identifier: CC0-1.0

# docs in https://pypsa-eur.readthedocs.io/en/latest/configuration.html#version
version: v2026.02.0

# docs in https://pypsa-eur.readthedocs.io/en/latest/configuration.html#tutorial
tutorial: false

# docs in https://pypsa-eur.readthedocs.io/en/latest/configuration.html#logging
logging:
  level: INFO
  format: "%(levelname)s:%(name)s:%(message)s"

# docs in https://pypsa-eur.readthedocs.io/en/latest/configuration.html#remote
remote:
  ssh: ""
  path: ""

# docs in https://pypsa-eur.readthedocs.io/en/latest/configuration.html#run
run:
  prefix: ""
  name:
  - cy2021-mds-coes-su
  scenarios:
    enable: true
    file: config/scenarios.noon.yaml

# docs in https://pypsa-eur.readthedocs.io/en/latest/configuration.html#foresight
foresight: overnight

# docs in https://pypsa-eur.readthedocs.io/en/latest/configuration.html#scenario
scenario:
  clusters:
  - "adm" # PyPSA-DE = 27, Form Energy = 52
  opts:
  - ""
  sector_opts:
  - ""
  planning_horizons:
  - 2030

# docs in https://pypsa-eur.readthedocs.io/en/latest/configuration.html#countries
countries:
- AT
- BE
- CH
- CZ
- DE
- DK
- FR
- IT
- LU
- NL
- PL
- SE

# docs in https://pypsa-eur.readthedocs.io/en/latest/configuration.html#snapshots
snapshots:
  start: "2021-01-01"
  end: "2022-01-01"
  inclusive: left

# docs in https://pypsa-eur.readthedocs.io/en/latest/configuration.html#co2_budget
co2_budget:
  2020: 0.72
  2025: 0.648
  2030: 0.45
  2035: 0.25 # 0.107 # FE input
  2040: 0.1
  2045: 0.05
  2050: 0.0

# docs in https://pypsa-eur.readthedocs.io/en/latest/configuration.html#electricity
electricity:
  max_hours:
    mds: 100
    coes: 200
  extendable_carriers: # No CCGT and OCGT # FE input
    StorageUnit: ["li-ion", "vanadium", "lair", "pair", "mds"]
    Store: ["H2", "coes"]


# docs in https://pypsa-eur.readthedocs.io/en/latest/configuration.html#atlite
atlite:
  default_cutout: "europe-2021-sarah3-era5"
  cutouts:
    "europe-1940-2024-era5":
      time:
      - '2021'
      - '2021'

# docs in https://pypsa-eur.readthedocs.io/en/latest/configuration.html#renewable
renewable:
  hydro:
    PHS_max_hours: 6 # 10 # FE input

# docs in https://pypsa-eur.readthedocs.io/en/latest/configuration.html#conventional
conventional:
  nuclear:
    p_max_pu: "data/nuclear_p_max_pu.csv"
    # p_min_pu: 0.5 # FE input

# docs in https://pypsa-eur.readthedocs.io/en/latest/configuration.html#lines
lines:
  s_max_pu: 0.7 # 0.5 # FE input
  dynamic_line_rating:
    correction_factor: 0.95
    max_voltage_difference: false # 30 # FE input
    max_line_rating: false # 1.5 # FE input

# docs in https://pypsa-eur.readthedocs.io/en/latest/configuration.html#transmission_projects
transmission_projects:
  include:
    manual: true # false # FE input
# docs-load in https://pypsa-eur.readthedocs.io/en/latest/configuration.html#load
load:
  fixed_year: 2021

# docs in https://pypsa-eur.readthedocs.io/en/latest/configuration.html#pypsa_eur
pypsa_eur:
  Generator:
  - onwind
  - "offwind-ac"
  - "offwind-dc"
  - "offwind-float"
  - "solar-hsat"
  - solar
  - ror

# docs in https://pypsa-eur.readthedocs.io/en/latest/configuration.html#sector
sector:
  transport: true
  heating: true
  biomass: false
  industry: false
  agriculture: false
  fossil_fuels: true
  district_heating:
    potential: 0.6 # 0.3 # FE input
    progress:
      2020: 0.0
      2025: 0.1
      2030: 0.25
      2035: 0.4 # 0.45 # FE input
      2040: 0.55
      2045: 0.75
      2050: 1.0
  bev_dsm: true
  bev_dsm_availability: 0.5 # 0.2 # FE input
  bev_charge_rate: 0.011 # 0.007 # FE input
  v2g: true
  land_transport_fuel_cell_share:
    2020: 0
    2025: 0
    2030: 0
    2035: 0
    2040: 0
    2045: 0
    2050: 0
  land_transport_electric_share:
    2020: 0
    2025: 0.05
    2030: 0.2
    2035: 0.45 # 0.30 # FE input
    2040: 0.7
    2045: 0.85
    2050: 1
  land_transport_ice_share:
    2020: 1
    2025: 0.95
    2030: 0.8
    2035: 0.55 # 0 # FE input
    2040: 0.3
    2045: 0.15
    2050: 0
  reduce_space_heat_exogenously: true
  reduce_space_heat_exogenously_factor:
    2020: 0.1
    2025: 0.09
    2030: 0.09
    2035: 0.11  # 0.21 # FE input
    2040: 0.16
    2045: 0.21
    2050: 0.29
  tes: false
  dac: true
  methanation: false
  co2_sequestration_potential:
    2020: 0
    2025: 0
    2030: 40
    2035: 100 # 22.3 # FE input
    2040: 180
    2045: 250
    2050: 250
  residential_heat:
    dsm:
      enable: true
    hydrogen_fuel_cell: true
  hydrogen_turbine: false
  hydrogen_underground_storage: true
  hydrogen_underground_storage_locations:
  - onshore  # no onshore # FE input
  - nearshore
  H2_network: false
  gas_network: false
  H2_retrofit: false


# docs in https://pypsa-eur.readthedocs.io/en/latest/configuration.html#costs
costs:
  year: 2030
  custom_cost_fn: data/custom_costs_base.csv

# docs in https://pypsa-eur.readthedocs.io/en/latest/configuration.html#clustering
clustering:
  mode: administrative
  administrative:
    level: bz
  temporal:
    resolution_sector: 3h

# docs in https://pypsa-eur.readthedocs.io/en/latest/configuration.html#solving
solving:
  options:
    load_shedding:
      enable: true
  solver:
    name: gurobi
    options: "gurobi-default"
