# -*- coding: utf-8 -*-
# SPDX-FileCopyrightText: Contributors to PyPSA-Eur <https://github.com/pypsa/pypsa-eur>
#
# SPDX-License-Identifier: MIT

### Technology

cy2021-base: # no mds, no res

  electricity:
    extendable_carriers:
      StorageUnit:
      - "li-ion 6h"
      - "li-ion 24h"
      - lfp
      - vanadium
      - lair
      - pair 24h
      - pair 100h

cy2021-lds: # mds + res

  electricity:
    extendable_carriers:
      StorageUnit:
      - "li-ion 6h"
      - "li-ion 24h"
      - lfp
      - vanadium
      - lair
      - pair 24h
      - pair 100h
      - mds
      - res 24h
      - res 100h
      - res 300h
      - res 500h

cy2021-lds-store: # res modelled as store+links

  electricity:
    extendable_carriers:
      StorageUnit:
      - "li-ion 6h"
      - "li-ion 24h"
      - lfp
      - vanadium
      - lair
      - pair 24h
      - pair 100h
      - mds
      Store:
      - H2
      - res

### Weather year
cy2023-lds: # weather year 2023

  snapshots:
    start: "2023-01-01"
    end: "2024-01-01"
    inclusive: left

  atlite:
    default_cutout: "europe-2023-sarah3-era5"
    cutouts:
      "europe-1940-2024-era5":
        time:
        - '2023'
        - '2023'
  load:
    fixed_year: 2023
    scaling_factor: 1.20 # 20% increase in EU27 industry demand from 2023 to 2030 (source: https://2026.entsos-tyndp-scenarios.eu/download/)

### Foresight
cy2021-lds-brownfield: # myopic foresight (w/ existing biomass CHP and nuclear + CGT and OCGT expansion allowed)

  foresight: myopic

  electricity:
    extendable_carriers:
      Generator:
      - solar
      - "solar-hsat"
      - onwind
      - "offwind-ac"
      - "offwind-dc"
      - "offwind-float"
      - CCGT
      - OCGT
      StorageUnit:
      - "li-ion 6h"
      - "li-ion 24h"
      - lfp
      - vanadium
      - lair
      - pair 24h
      - pair 100h
      - mds
      - res 24h
      - res 100h
      - res 300h
      - res 500h
      Store: ["H2"]

  sector:
    biomass: true

### Planning horizon
cy2021-lds-2040: # 2040

  scenario:
    planning_horizons:
    - 2040

  load:
    fixed_year: 2021
    scaling_factor: 1.31 # 31% increase in EU27 industry demand from 2021 to 2040 (source: https://2026.entsos-tyndp-scenarios.eu/download/)
